//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;
using Cruds.Domain;
using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : dbClientes
	/// Data Source    : localhost\B1
	/// Server Version : 14.00.1000
	/// </summary>
	public partial class DbClientesDB : LinqToDB.Data.DataConnection
	{
		public ITable<Cliente>     Clientes    { get { return this.GetTable<Cliente>(); } }
		
		public DbClientesDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbClientesDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbClientesDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbClientesDB(LinqToDbConnectionOptions<DbClientesDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	
	public static partial class TableExtensions
	{
		public static Cliente Find(this ITable<Cliente> table, int Codigo)
		{
			return table.FirstOrDefault(t =>
				t.Codigo == Codigo);
		}
	}
}

#pragma warning restore 1591
